### ISSUE TITLE
KeyError: 'content-length'

### ISSUE THREAD

**Issue by reversebrain** [infosec-au/enumXFF#4]
I am trying to use the tool like this:

`python enumXFF.py -t http://10.10.10.62:56423/ --badcl 31 -r 192.168.0.0-192.168.255.255 -w 10`

But I receive this error:

`Traceback (most recent call last):
  File "enumXFF.py", line 37, in <module> 
    if response.headers['content-length'] > args.badcl:
  File "/usr/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'`

What is wrong?

**Comment by reversebrain** [comment]
The problem was that my response didn't have Content-Lenght header.
