### ISSUE TITLE
Content-length error

### ISSUE THREAD

**Issue by justpentest** [infosec-au/enumXFF#5]
C:\Python27\enumXFF-master\enumXFF-master>python enumXFF.py -t https://bitdefender.com/ -badcl 234 -r 192.168.0.0-192.168.255.255
usage: enumXFF.py [-h] -t TARGET -cl BADCL -r RANGE [-w WORKERS] [-o OUTPUT]
enumXFF.py: error: argument -cl/--badcl is required

C:\Python27\enumXFF-master\enumXFF-master>python enumXFF.py -t https://bitdefender.com/ --badcl 234 -r 192.168.0.0-192.168.255.255
  0%|                                                                                        | 0/65536 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "enumXFF.py", line 37, in <module>
    if response.headers['content-length'] > args.badcl:
  File "C:\Python27\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

**Comment by defrindr** [comment]
#6
